### ISSUE TITLE
Mapbox streets-v12 style trys to load invalid fonts

### ISSUE THREAD

**Issue by vespertilian** [openlayers/ol-mapbox-style#1001]
As you can see in this image. 

Using the map-box vector layer demo. When you set the style to streets-v12 it tries to download fonts for an invalid domain. 

https://openlayers.org/en/latest/examples/mapbox-vector-layer.html

<img width="1004" alt="font-error-for-streets-v-12" src="https://github.com/openlayers/ol-mapbox-style/assets/441418/c64ac27c-516e-495c-b2d2-88be58000c4b">

**Comment by ahocevar** [comment]
This is because streets-v12 uses the font "Din Pro", which is not available on Fontsource. See https://github.com/openlayers/ol-mapbox-style#font-handling for how ol-mapbox-style handles fonts, and how you can modify the style document to point it to fonts you provide yourself.

You can also just add the missing web font using web fonts in the css of the document that contains the map.
