### ISSUE TITLE
Mapbox styles default to serif font even when serif font is specified

### ISSUE THREAD

**Issue by t-muko** [openlayers/ol-mapbox-style#448]
The font substitution with ol-mapbox-style is not very well documented. In most cases, the chosen font seems to be serif font, when in mapping applications usually sans-serif fonts are preferred due to legibility.

This is probably a browser dependent behaviour, which type is specified as fall back font family.

Expectation:
1. When a sans-serif font is specified in style file, sans-serif font would be used.
2. Documentation how to do explicit font substitution or default setting

**Comment by ahocevar** [comment]
Since mapbox-gl-js uses "Arial Unicode MS Regular" as default fallback font, I agree our default fallback should be a sans-serif font too. This might even make sense for upstream OpenLayers. Regarding your expectations, ol-mapbox-style can use Google webfonts and fonts that are available in the browser by default. This is documented in the [README](https://github.com/openlayers/ol-mapbox-style/blob/bf18cbc4f4a01795068a66464a5d153e71b553e6/README.md):

> Only commonly available system fonts and Google Fonts will automatically be available for any text-font defined in the Mapbox Style object. It is the responsibility of the application to load other fonts. Because ol-mapbox-style uses system and web fonts instead of PBF/SDF glyphs, the font stack is treated a little different: style and weight are taken from the primary font (i.e. the first one in the font stack). Subsequent fonts in the font stack are only used if the primary font is not available/loaded, and they will be used with the style and weight of the primary font.

The default fallback for canvas rendering in the browser is `serif`.
