### ISSUE TITLE
vector layer render order 

### ISSUE THREAD

**Issue by mclkyo** [openlayers/ol-mapbox-style#583]
i have add a vectory layer use olms style, z-index is 0, and add a raster layer with xyz image z-index is 1
but poi source in the vector layer is alway render upon the raster layer

![image](https://user-images.githubusercontent.com/9249885/172555257-f12c47c4-306a-4564-ac51-7e7e590f759b.png)
![image](https://user-images.githubusercontent.com/9249885/172555289-d92c48ae-b653-4ff9-bec3-982dc0c2a12d.png)

my code like this 
![image](https://user-images.githubusercontent.com/9249885/172555514-15896354-5c84-4b98-9283-a783929fb72b.png)

 my openlayer version is 6.14.0  olms is 8.1.2

**Comment by ahocevar** [comment]
This is because of decluttering, which considers all layers and renders the result on top of other layers. You have two options:

1. Disable decluttering, i.e. set `declutter: false` instead of `declutter: true`
2. Configure the `VectorTile` layer with `className: 'vectortile'`. This may cause problems on mobile devices though, because id adds a significant memory penalty because it prevents output canvases from being reused for subsequent layers.

**Comment by mclkyo** [comment]
thanks,it work fine
if i use declutter: false, the poi text is so confusion. is it possible set text ovelap style in the mapbox style json?

**Comment by ahocevar** [comment]
`text-allow-overlap` is not supported.
