### ISSUE TITLE
raster layer opacity gets overwritten on zoom

### ISSUE THREAD

**Issue by AlenKelemen** [openlayers/ol-mapbox-style#675]
OSM raster is defined in mapbox style.js.
In openlayers we use layer.setOpacity() to set opacitiy different from one set in mapbox style.js.
Layer gets that opacity until zoom is used, than its opacitiy gets restored to one set in mapbox style.js.
So it is not possible to use layer.setOpactiy() on raster layers from mapbox style.js

For geojson layers this is not the case as opacity retains as set in layer.setOpacitiy

**Comment by ahocevar** [comment]
This is because the Mapbox Style specification has a `raster-opacity` property that gets applied to the OpenLayers layer instance for that raster layer. There is no such thing for geojson layers.

In theory, the correct way to change opacity for a raster layer would be to change the `raster-opacity` property of the respective layer style.

However, this won't get respected because the function cache key for the expression function that evaluates the current opacity does not take the opacity into account. A possible workaround would be to also change the layer id in the Mapbox Style object when changing the opacity, but that's a bit awkward. So I think we can improve the situation by taking the opacity into account for the function cache key. I'm going to create a pull request for this.

**Comment by ahocevar** [comment]
Will be fixed with #676.
